### ISSUE TITLE
[BOT] Feature - Add Australian grades

### ISSUE THREAD

**Issue by valtism** [derekantrican/MountainProject#64]
Hey there 👋

Love the bot, but something that would be super useful would be if Australian grades were added to the list of grades on a climb.

I remember a while ago trying to make a PR for this, but I think I got confused with the code or something else happened.

If this is an easy thing to do, I would very much appreciate it, as would other Aussie climbers.

Thanks!

**Comment by derekantrican** [comment]
Thanks for the suggestion! I'll look into it and let you know if I have questions for you as I'm not familiar with grade systems outside of YDS/Hueco

**Comment by derekantrican** [comment]
FYI this was added in https://github.com/derekantrican/MountainProject/commit/825f994704a4bb1f943d64c9ea6ce331bffaca7b
